spring.application.name=chibchaweb
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/chibchaweb
spring.datasource.username=chibcha_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=app

jwt.secret=chibchaweb-secret-key-that-is-at-least-256-bits-long-for-hmac-sha-algorithm
jwt.expiration=86400000

